name: Build msyh Image

on:
  push:
   branches:
     - main
   paths:
     - ".github/workflows/build-image-msyh.yaml"
     - "Dockerfile-msyh"
     - "install-wechat.sh"
     - "cmd.sh"

jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      # 使用这个镜像，不然Docker无法打包镜像
      image: catthehacker/ubuntu:act-latest

    steps:
      - name: Login to Repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build 3.9.8.25 version with msyh
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lxh01/wxhelper-docker:3.9.8.25-v2-msyh
          file: Dockerfile-msyh
          build-args: |
            WECHAT_URL=https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.8.25/WeChatSetup-3.9.8.25.exe
            WXHELPER_URL=https://github.com/ttttupup/wxhelper/releases/download/3.9.8.25-v2/wxhelper.dll

      - name: Build 3.9.5.81 version with msyh
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lxh01/wxhelper-docker:3.9.5.81-v11-msyh
          file: Dockerfile-msyh

      - name: Build 3.9.2.23 version with msyh
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lxh01/wxhelper-docker:3.9.2.23-v9-msyh
          file: Dockerfile-msyh
          build-args: |
            WECHAT_URL=https://github.com/tom-snow/wechat-windows-versions/releases/download/v3.9.2.23/WeChatSetup-3.9.2.23.exe
            WXHELPER_URL=https://github.com/ttttupup/wxhelper/releases/download/3.9.2.23-v9/wxhelper.dll
